version: '3.1'
services:
  db:
    image: mariadb:10.6.7
    restart: always
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: q
      MARIADB_DATABASE: test
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"